### ISSUE TITLE
Question about the configuration in the command line 

### ISSUE THREAD

**Issue by benlin1996** [Atharv24/SnakeGym#1]
Thanks for the wonderful code. I try to change the default configuration, but I fail to do this. For example, if I want to change the target reward and keep other as default, how should I complete this? Thanks

**Comment by Atharv24** [comment]
Copy the `Default_SP.ini` config file and change the **TARGET_REWARD** value there.
As of now the training or testing scripts doesn't assume any defaults for config variables, so you must specify all of them. However, feel free to update this and push to this repo :)

**Comment by benlin1996** [comment]
Get it. Thanks for your help
