### ISSUE TITLE
is there a time limited?

### ISSUE THREAD

**Issue by benlin1996** [Atharv24/SnakeGym#2]
Is this game was set to be time limited? If so, can you tell me which line of code control this? (I cant find the code that control this) Thanks for your help again

**Comment by Atharv24** [comment]
There is no time limit currently.
While training the game goes on until the target reward (specified in config) is reached in 4/5 games, with the snake resetting whenever it dies.
While testing the game goes on for a fixed number of snake deaths (specified as arguments in the terminal).

**Comment by benlin1996** [comment]
Thanks again for your help
